### PR TITLE
Add support for Laravel 10 and Improve code

### PR DESCRIPTION
**Pull request by mateusjunges**
### Supported laravel/php versions
As `Laravel 8` reached `EOL`, this PR drops support for this laravel version, supporting only `Laravel 9` and `Laravel 10`.
Also, support for `php 8.0` was dropped, and the new minimum required PHP version is `8.1`

### New config option to return response as DTO
This PR introduces a new config option that enables you to get the location response as an instance of `InteractionDesignFoundation\GeoIP\LocationResponse`. This ensure that all providers will have the same response, so you can switch between different location providers easily. Before this PR, the `IpGeoLocation` and `IpFinder` providers had a different response when hydrated.

To enable it, you just need to change/add this option in `config/geoip.php` to true:
```php
'should_use_dto_response' => true,
```

### Simplified `HttpClient`
This PR changes the `HttpClient` to use Laravel `Http` facade instead of `curl` to perform requests.
Also, no providers used the `headers` returned by the previous client, so this has been removed.

### `IPData` provider implementation
This provider implementation was incorrect, as the api URL returned a `404` response. I updated the code to match the documentation.

I also added tests for missing location providers

### CODE REVIEW

**Review by lptn — CHANGES_REQUESTED** [review]
As this is package we shared wit community under our vendor name - it requires more love. Can you please also update CI - https://github.com/InteractionDesignFoundation/laravel-geoip/blob/main/.github/workflows/run-tests.yml (use laravel 10, PHP 8.2). Thanks!

**Comment by mateusjunges** [comment]
Should we drop support for Laravel 8 as well?

**Comment by lptn** [comment]
>Should we also drop support for Laravel 8?

Yes, it's EOL

image


Also, feel free to borrow some ideas from upstream PRs (pending), e.g. https://github.com/Torann/laravel-geoip/pull/224 and prepare a good stable release, decent to share with the community

**Review by lptn — CHANGES_REQUESTED** [review]
hey @mateusjunges 
I appreciate your work here, how about moving improvements into a separate PR where we can discuss them in details?  Especially DTO idea is not so clear to me (why we will support 2 types/logic branches at the same time and what are benefits).

The idea of this form is to provide an opportunity for a  smooth migration for the community from original package to our fork (as more maintainable). Any breaking changes are better to do after fixing original issues

**Pull request closed without merging**
